### PR TITLE
Test Pull Request

### PR DESCRIPTION
**Pull request by aitorsanz**
First pull request for test

### CODE REVIEW

**Comment by RecuencoJones** [comment]
Closing pull request. Please avoid this type of PRs.

**Comment by aitorsanz** [comment]
ok disculpa había entendido a mal a Pellicer, solo quería hacer un commit de prueba como ha dicho hoy en clase

**Comment by RecuencoJones** [comment]
Please, try to use english, also you can try this type of stuff in your repository creating branches and creating pull requests against your master.

**Comment by aitorsanz** [comment]
Ok I'll be more careful in next tests

Thanks and sorry for the disturbances

**Pull request closed without merging**
