### PR TITLE
Description.md update

### PR DESCRIPTION
**Pull request by paul-huszak**
Added gradle config section in the _**description.md**_ file.

### CODE REVIEW

**Comment by fjlopez** [comment]
@paul-huszak, your CI isn't working yet. Can you launch it?

**Comment by paul-huszak** [comment]
Hello,

Sorry for the late reply, I’ve just checked my git branch, and it’s still
on no status mode.

I’ve followed all the GUIDE steps but I still cannot change that status.
What should I do? What is the correct way to launch the CI? Somehow I think
I forgot that step.

Thanks for your patience.

Paul

**Comment by fjlopez** [comment]
The CI workflow is launched automatically on push and pull requests.

```yaml
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```

Therefore, in order to trigger your CI workflow, you must clone, modify a file and push the change to GitHub.

**Comment by paul-huszak** [comment]
Okay it is solved now. I manually ran a CI workflow and now my status
has been updated. Anyways I would like to ask you about this topic tomorrow
during the practice session.

Thanks for your help again.

**Pull request merged**
