### PR TITLE
EndPoint

### PR DESCRIPTION
**Pull request by thdgm**
I have created a button on the welcome page, which when pressed navigates to the /first page, which is an end point. For which I have created a controller and it returns a string that is displayed on the screen.

### CODE REVIEW

**Comment by thdgm** [comment]
Also when executing it in intellij idea, I have added the following line to the application.property file, to suppress minor errors that appeared: logging.level.org.springframework.boot.autoconfigure = ERROR

**Comment by thdgm** [comment]
I have had a problem with the previous commits, as they were not the correct version. The last one is. In the latter, the created controller shows the content of a file that I have created in html, called page1.html. All this after pressing the button on the welcome page.

**Comment by fjlopez** [comment]
*PR accepted.*

**Comment by fjlopez** [comment]
Localizado commit. Resolviendo problema.

**Pull request merged**
