### PR TITLE
added comentaries about annotations on test cases

### PR DESCRIPTION
**Pull request by danieluned**
I have put the suggestions about Java comentaries. Now the annotations are in block and the start of the Class.

### CODE REVIEW

**Comment by fjlopez** [comment]
Javadoc comments are tricky. You should build them. Add the following snipped to your `build.gradle`:
```
task testJavadoc(type: Javadoc) {
    source = sourceSets.test.allJava
    classpath = sourceSets.test.compileClasspath
    destinationDir = file("${buildDir}/docs/testjavadoc")
    println (title == null? '<null>' : title)
}
```
Then run:
```bash
$ gradle testJavadoc
```
This will cause the following message error:
```
lab1-git-race-master/src/test/java/es/unizar/webeng/hello/HelloControllerUnitTest.java:16: error: unknown tag: RunWith
*   @RunWith(SpringRunner.class)  Annotation from Junit, Junit will run using Spring's testing support.
    ^
/Users/javier/Downloads/lab1-git-race-master/src/test/java/es/unizar/webeng/hello/HelloControllerUnitTest.java:18: error: unexpected text
*       {@link http://junit.sourceforge.net/javadoc/org/junit/runner/RunWith.html}
        ^
lab1-git-race-master/src/test/java/es/unizar/webeng/hello/HelloControllerUnitTest.java:20: error: unknown tag: WebMvcTest
*   @WebMvcTest(HelloController.class)  Start the Spring application context without the server, 
    ^
lab1-git-race-master/src/test/java/es/unizar/webeng/hello/HelloControllerUnitTest.java:22: error: unexpected text
*       {@link https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/autoconfigure/web/servlet/WebMvcTest.html}
        ^
/lab1-git-race-master/src/test/java/es/unizar/webeng/hello/HelloControllerUnitTest.java:24: error: unknown tag: Value
*   @Value("${app.message:Hello World}")  We can inject the value from a file into 
    ^
lab1-git-race-master/src/test/java/es/unizar/webeng/hello/HelloControllerUnitTest.java:27: error: unexpected text
*       {@link https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/beans/factory/annotation/Value.html}
        ^
lab1-git-race-master/src/test/java/es/unizar/webeng/hello/HelloControllerUnitTest.java:29: error: unknown tag: Autowired
*   @Autowired This annotation will scan on the packpage for annotations like @Controller,
    ^
lab1-git-race-master/src/test/java/es/unizar/webeng/hello/HelloControllerUnitTest.java:30: error: unknown tag: Component
*        @Component, @Repository or simple bean, to auto-inject all the necesary in the variable.
         ^
lab1-git-race-master/src/test/java/es/unizar/webeng/hello/HelloControllerUnitTest.java:31: error: unexpected text
*       {@link https://docs.spring.io/spring-framework/docs/2.5.x/api/org/springframework/beans/factory/annotation/Autowired.html}
        ^
lab1-git-race-master/src/test/java/es/unizar/webeng/hello/StaticContentUnitTest.java:34: error: unknown tag: Before
     * @Before specifies that it should be executed first automatically, previous to any tests.
       ^
10 errors
```
Why ... because `@` is a special element in Javadoc. I recommend you to read [this](http://facweb.northseattle.edu/voffenba/class/csc143/review/JavadocBasics.html).

**Comment by danieluned** [comment]
Thanks for helping me with Javadoc errors. I added it to gradle and debugged whole project. I fixed another file that contains Javadoc errors.  Always error on @.  I removed it.

**Comment by fjlopez** [comment]
Note that the Javadoc tool is very smart and it is able to resolve these references to the location of the documentation (if available). You can find a lot of examples in the [official documentation](http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html).

**Comment by fjlopez** [comment]
I think that you can improve it! As you can see, all your comments appears on the **See also** section. 

captura de pantalla 2017-09-26 a las 14 33 25

I think that this example can help you:

captura de pantalla 2017-09-26 a las 14 36 02

**Comment by danieluned** [comment]
Like i see, i only can put one @see in one block comment not? Is a good practice if i put each definition of annotation in diferent block comment?

**Comment by fjlopez** [comment]
You can use several  `@see` tags. They are presented in the same block in alphabetic order. Read the documentation about `@see` tags at the [official javadoc documentation](http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html) because there are three variations.

**Pull request merged**
