### PR TITLE
Small test that returns a Disney character according to the ansewrs given.

### PR DESCRIPTION
**Pull request by IgnacioSan22**

### CODE REVIEW

**Comment by fjlopez** [comment]
Resolve the conflicts and I will merge your code. I have proposed a possible enhancement that deserves a :gift: that you optionally can do (but you can also think in something different and gaint also the :gift:).

**Comment by IgnacioSan22** [comment]
Using Vue or similar instead of JSP would count as an enhancement to get a 🎁??

**Comment by fjlopez** [comment]
Yes, of course. Your should rid of those pesky JSP.

**Comment by fjlopez** [comment]
Please, resolve ASAP the current conflicts so I can merge your pull request. We can review in a future pull request your enhancement. 
```
README.md
src/main/webapp/WEB-INF/jsp/wellcome.jsp
```

**Comment by IgnacioSan22** [comment]
Okey, I've alredy solved the conflicts. I'm trying to add thymeleaf to the proyect, but it's still not working.

**Pull request merged**
