### PR TITLE
Updated following markdown standard

### PR DESCRIPTION
**Pull request by asierhandball**

### CODE REVIEW

**Comment by RecuencoJones** [comment]
Fix conflicts before merging

**Comment by fjlopez** [comment]
Sync your repo and fix the conflict.  Then warn me.

**Comment by RecuencoJones** [comment]
Hi @asierhandball, there was an issue with SonarQube that made the build fail, please update your repo and this pull request to rebuild with TravisCI

**Comment by fjlopez** [comment]
LGTM

**Pull request merged**
