### PR TITLE
new improves to the website

### PR DESCRIPTION
**Pull request by ZgzInfinity**
i have modified all the mistakes

### CODE REVIEW

**Comment by fjlopez** [comment]
If so, please close #33 first

**Comment by ZgzInfinity** [comment]
so it's all correct now?

**Comment by fjlopez** [comment]
No, `your visits` is not initialised. Check it.

**Comment by ZgzInfinity** [comment]
Yes, it's a variable which is not initialised at the beginnig but when you execute the method this part of  the code gives a value to the variable and it seems to work correctly.

 if (index == -1) {
         	r.setNumberVisits(1);
         	listaIps.addLast(r);
         	**yourVisits** = 1;
         }
         else {
         	r = listaIps.get(index);
         	int times = r.getNumberVisits() + 1;
         	**yourVisits** = times;
         	r.setNumberVisits(times);
         	listaIps.add(index, r);
         }

So, excuse me, but i dont understand how i should do it

**Comment by fjlopez** [comment]
I see. The key issue here is that  `yourVisits` is a shared variable with race conditions. Convert `yourVisits` in a local variable in `welcome`. This implies that `monitorizeNumberOfVisits` returns the number of visits. That will fix all the issues.

**Pull request closed without merging**
