### PR TITLE
Added brief information about the last commit of the repository

### PR DESCRIPTION
**Pull request by DanFzgz**

### CODE REVIEW

**Comment by fjlopez** [comment]
You  can solve the conflict with the README so I can merge your code, and later do a new pull request to get the 🎁

**Comment by DanFzgz** [comment]
The conflict with the README is solved and I have also started working on the refactor you suggested.

**Comment by DanFzgz** [comment]
Code refactored using [Object Oriented Github API](https://github.jcabi.com/index.html), hope everything is ok since I messed up a bit with GitHub.

**Comment by fjlopez** [comment]
Nearly perfect. Add a test showing that your code works and done (with :gift:)! 
Remember that you should also resolve the conflicts with:

```
README.md
build.gradle
src/main/java/es/unizar/webeng/hello/HelloController.java
```

**Comment by fjlopez** [comment]
If you wish you can solve the conflicts in:
```
README.md
build.gradle
src/main/java/es/unizar/webeng/hello/HelloController.java
```
so I can merge your code. Later you can do the challenge.

**Pull request merged**
