### PR TITLE
Added 'How to test & run the project' section to description.md

### PR DESCRIPTION
**Pull request by pikanachi**

### CODE REVIEW

**Comment by fjlopez** [comment]
Please, fix the issues and I will merge this PR.

**Comment by pikanachi** [comment]
I can't find any issues. Could you give me more details? Thank you!

**Comment by fjlopez** [comment]
Check the review.

**Review by pikanachi — COMMENTED** [review]
### readme.md
Added my own username to the table.
### description.md
Added new section `How to test & run the project` with instructions about the prerequisites for the project and the instructions to test and run the project.

**Comment by fjlopez** [comment]
Please, check the review here https://github.com/UNIZAR-30246-WebEngineering/lab1-git-race/pull/2/files/534226f51adec6cb951025122bb25c1c9f05a389

**Review by fjlopez — CHANGES_REQUESTED** [review]

**Comment by fjlopez** [comment]
Sorry, the reviews were unfinished. Now they are visible.

**Comment by pikanachi** [comment]
Is it ok now?

**Comment by fjlopez** [comment]
Accepted.

**Pull request merged**
