### PR TITLE
Added code explanation to controller/HelloController.kt

### PR DESCRIPTION
**Pull request by Ernesting**

### CODE REVIEW

**Comment by fjlopez** [comment]
Please, fix the issues found during the review. Check https://github.com/UNIZAR-30246-WebEngineering/lab1-git-race/pull/5/files/400b48e069cf6c8614de7f6d045ffa0997762381

**Review by fjlopez — CHANGES_REQUESTED** [review]

**Comment by fjlopez** [comment]
Sorry, the reviews were unfinished. Now they are visible.

**Review by Ernesting — COMMENTED** [review]
Done

**Review by fjlopez — APPROVED** [review]

**Comment by fjlopez** [comment]
Accepted.

**Pull request merged**
