### PR TITLE
PR Jorge: Spring II - use WebClient for sync request - Twitter Timeline functionality

### PR DESCRIPTION
**Pull request by jgarciapueyo**
Added a new endpoint /twitter/{user} that prints the last 5 tweets of _user_. This is done with WebClient, provided by Spring WebFlux, using the Twitter API.

### CODE REVIEW

**Comment by jgarciapueyo** [comment]
For implementing the functionality using WebClient I've had to learn about [Reactor Core](https://github.com/reactor/reactor-core) that is used as the reactive library choice for [Spring Webflux](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-reactive-api).

To get a response with WebClient the easiest method is the `retrieve()` [method](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-client-retrieve). After that, we transform it to a Mono or Flux type variable. My question is how could we use Mono or Flux together with a Thymeleaf template. I have not been able to find useful information about this, this is why I've had to use the `block()` method when doing the request.

**Comment by fjlopez** [comment]
Wrap the flux or mono object with `ReactiveDataDriverContextVariable` in the MVC method, add it to the model and return the view.  See https://mkyong.com/spring-boot/spring-boot-webflux-thymeleaf-reactive-example/

Even you should let bodyToFlux to convert the answer into a Tweet. Note that if the Tweets are encoded as `application/stream+json`

```java
IReactiveDataDriverContextVariable res = new ReactiveDataDriverContextVariable (client.get()
                    .uri("?screen_name=" + user)
                    .header("authorization", "Bearer " + twitter_bearer)
                    .retrieve()
                    .flatMapMany(r -> r.bodyToFlux(Tweet.class)), 5);
model.addAttribute("tweets", res);
```

If tweets are encoded as `application/stream+json` you can try to get the JSONObject as mono object and then do a flatmap to create as many Tweets as possible as flux. e.g.

```java
IReactiveDataDriverContextVariable res = new ReactiveDataDriverContextVariable(mono.flatMap(jsonObject -> .... returns a list of Tweets[]).flatMapMany(Flux::fromIterable))
```

Test which is the best approach, and use it. Anyway you have the :gift: but will be better for your fellows if your example is complete.

**Comment by jgarciapueyo** [comment]
I have implemented the functionality as you have suggested (after dealing with the horrible Twitter API v1.1 that does not allow to select the fields when retrieving the tweets, i think this is one of the reasons GraphQL appeared and a technology that could be interesting to talk about in class).

```java
Flux<Tweet> res = client.get()
                    .uri("?screen_name=" + user + "&count=5")
                    .header("authorization", "Bearer " + twitter_bearer)
                    .retrieve()
                    .bodyToFlux(Tweet.class);
            
            model.addAttribute("user", user);
            model.addAttribute("tweets", new ReactiveDataDriverContextVariable(res, 5));
```
However, I think there are conflicts between 'spring-boot-starter-webflux' and 'spring-boot-starter-web'.
If both are added as dependencies, the thymeleaf template shows the tweets as the hashed variable: org.thymeleaf.spring5.context.webflux.ReactiveDataDriverContextVariable@20f459fc.

If I delete the dependency 'org.springframework.boot:spring-boot-starter-web', everything works fine and the tweets are shown correctly but the tests do no pass because there are classes not found: `Could not initialize class org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTypeExcludeFilter.`

I have found that other people have this problem (https://stackoverflow.com/a/59145920). It seems like 'org.springframework.boot:spring-boot-starter-web' as dependency disables thymeleaf reactive mode. I don't know how to proceed or fix this error.

**Comment by jgarciapueyo** [comment]
It looks like it is not recommended to use  'spring-boot-starter-webflux' and 'spring-boot-starter-web' together because this results in Spring Boot auto-configuring Spring MVC, not WebFlux. This is what was blocking Thymeleaf to use templates in a reactive manner.

In [Spring Documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-webflux) it shows how this can be fixed:
`Adding both spring-boot-starter-web and spring-boot-starter-webflux modules in your application results in Spring Boot auto-configuring Spring MVC, not WebFlux. This behavior has been chosen because many Spring developers add spring-boot-starter-webflux to their Spring MVC application to use the reactive WebClient. You can still enforce your choice by setting the chosen application type to SpringApplication.setWebApplicationType(WebApplicationType.REACTIVE).`

**Pull request merged**
