### PR TITLE
Run and build documentation + name in table

### PR DESCRIPTION
**Pull request by Ibon2**

### CODE REVIEW

**Comment by fjlopez** [comment]
Please, fix the issues found. I will accept this PR after fixes. Note that probably you should sync your work before the merge.

**Comment by Ibon2** [comment]
Which issues, I don't see them. Where can I found them?

**Comment by fjlopez** [comment]
Check the reviews https://github.com/UNIZAR-30246-WebEngineering/lab1-git-race/pull/1/files/fb6f4d48edbca6f25591103df903b0510c5659da

**Review by Ibon2 — COMMENTED** [review]
Checked the reviews

**Comment by fjlopez** [comment]
If you have made changes locally, you should push them to your GitHub repo. Alternatively, you can edit and modify the files in your GitHub repo.

**Review by fjlopez — CHANGES_REQUESTED** [review]

**Comment by fjlopez** [comment]
Sorry, the reviews were unfinished. Now they are visible.

**Comment by fjlopez** [comment]
Do not close your PR, just do a push to your repo and the changes automatically will apear here.

**Review by Ibon2 — COMMENTED** [review]
Reviews checked in the last merge

**Review by Ibon2 — COMMENTED** [review]
Everything is correct.

**Review by fjlopez — APPROVED** [review]
Added a missing line.

**Comment by fjlopez** [comment]
Hecho

**Pull request merged**
